name: testkl
favicon: null
layout_spectrum: 0.99853
typography_spectrum: 0.4429074241014075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 0.75256
  saturation: 0.541911
  rhythmicContrast: 0.484989
purpose:
  - name: null
    item: null
    url: null
