analytics: {}
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0
  lightness: 0.75256
  rhythmicContrast: 0.484989
  saturation: 0.541911
cta: {}
layout_spectrum: 0.004504
name: testkl
opengraph: {}
purpose: {}
typography_spectrum: 0.4429074241014075
